export const FETCH_QUOTES = 'FETCH_QUOTES';
export const FETCH_QUOTES_FULFILLED = 'FETCH_QUOTES_FULFILLED';
export const FETCH_QUOTES_REJECTED = 'FETCH_QUOTES_REJECTED';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_FULFILLED = 'FETCH_USER_FULFILLED';
export const FETCH_USER_REJECTED = 'FETCH_USER_REJECTED';

export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_FULFILLED = 'LOGIN_USER_FULFILLED';
export const LOGIN_USER_REJECTED = 'LOGIN_USER_REJECTED';
